### ISSUE TITLE
Wordiscover download link in Github. Site http://wordiscover.cint.io not working.

### ISSUE THREAD

**Issue by carloscadux** [sorrell/wordiscover#2]
Hi.
Wordiscover is brilliant work of yours! 
It's an essential extension to search properly in MS Word. Actually, Microsoft should incorporate such functionality natively.
I was going to recommend Wordiscover to my students, and when I accessed your site (http://wordiscover.cint.io/), it didn't load.
By chance will your website become functional again?
Otherwise, have you thought about releasing and providing a download link to Wordiscover here, within Github?
Thank you!
Carlos

**Comment by sorrell** [comment]
Thanks for the feedback! I've re-established https://wordiscover.cint.io and also put the files in the Releases section here on Github https://github.com/sorrell/wordiscover/releases/tag/0.1.0

**Comment by carloscadux** [comment]
> Thanks for the feedback! I've re-established https://wordiscover.cint.io and also put the files in the Releases section here on Github https://github.com/sorrell/wordiscover/releases/tag/0.1.0

Thank you very much 👍
